[package]
name = "build_libtika"
version = "0.1.0"
edition = "2024"

[dependencies]
fs_extra = { version = "1.3.0" }
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
zip = "2.2.0"
flate2 = "1.0.33"
tar = "0.4.41"
const_format = "0.2.35"
which = "8.0.0"
