name: CI

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # platform: [ubuntu-latest, windows-latest, macos-latest]
        # platform: [macos-latest]
        platform: [ubuntu-latest]
        # platform: [windows-latest]

    runs-on: ${{ matrix.platform }} 

    steps:
    - uses: actions/checkout@v4

    # - name: Build project
    #   shell: bash
    #   run: make build

    # - name: Run tests
    #   shell: bash
    #   run: make test

    - name: Run tests
      shell: bash
      run: make uselib