name: CI

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest]
        # platform: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }} 

    steps:
    - uses: actions/checkout@v4

    - name: Build project
      shell: bash
      run: make build

    - name: show pkg
      shell: bash
      run: ls -al pkg

    - name: Run tests
      shell: bash
      run: make test